#+BEGIN_EXAMPLE
                            ________________

                             TEMPLATE PAPER

                             Tedward Erker
                            ________________
#+END_EXAMPLE

Table of Contents \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

1 Introduction 2 Methods 3 Results .. 3.1 first sublevel .. 3.2 second
sublevel 4 Discussion 5 Conclusion

** ##+OPTIONS: toc:t num:nil date:t
   :PROPERTIES:
   :CUSTOM_ID: options-toct-numnil-datet
   :END:

* 1 Introduction
  :PROPERTIES:
  :CUSTOM_ID: introduction
  :END:

A bunch of text goes here. ext goes here. A bunch of text goes here. A
bunch of text goes here.

Well let's say that someone wants to add a bunch of text here. Well
let's say that someone wants to add a bunch of text here.Well let's say
that someone wants to add a bunch of text here.Well let's say that
someone wants to add a bunch of text here.

* 2 Methods
  :PROPERTIES:
  :CUSTOM_ID: methods
  :END:

test citation [nelson\_etal\_2009]

* 3 Results
  :PROPERTIES:
  :CUSTOM_ID: results
  :END:

3.1 first sublevel _{_{~}_{_{_{_{~}}}}}~~

What did you find? Something, anything?

* 4 Discussion
  :PROPERTIES:
  :CUSTOM_ID: discussion
  :END:

Maybe I'll have an equation in the discussion
((1.96\sqrt{\frac{(.2)(.8)}{584}}). And then perhaps a superscript like
5000 m\^2, followed by the subscript O\_2.

add a sublevel _{_{_{~}}_{_{_{~}}}~}

much much much more interesting things.

* 5 Conclusion
  :PROPERTIES:
  :CUSTOM_ID: conclusion
  :END:

Bibliography ============= [nelson\_etal\_2009] Nelson, McRoberts,
Holden, & Bauer, Effects of Satellite Image Spatial Aggregation and
Resolution on Estimates of Forest Land Area, @@html:<i>@@{International
Journal of Remote Sensing}@@html:</i>@@, @@html:<b>@@30(8)@@html:</b>@@,
1913-1940 (2009). @@html:<a
  href="http://dx.doi.org/10.1080/01431160802545631">@@link@@html:</a>@@.
@@html:<a
  href="http://dx.doi.org/10.1080/01431160802545631">@@doi@@html:</a>@@.
